### ISSUE TITLE
关于write的并发问题

### ISSUE THREAD

**Issue by payall4u** [AlexZFX/engine#1]
write函数中的这部分代码似乎会产生并发问题
``` java
        // ...
        int hash = valueFileHash(numkey);
        int off = valueOffsets[hash].getAndIncrement();
        try {
            ByteBuffer keyBuffer = keyMappedByteBuffers[hash].slice();
            keyBuffer.position(keyOffsets[hash].getAndAdd(KEY_AND_OFF_LEN));
            keyBuffer.putLong(numkey).putInt(off);
       // ...
```
假设两个线程同时调用write方法并且产生的hash相同时，有如下执行顺序：
1. t1执行`keyBuffer.position()`      ->    buffer位置变成了x
2. t2执行`keyBuffer.position()`    ->    buffer位置变成了x + 16
3. t1执行`keyBuffer.putLong()`    ->    buffer中为 [key1]
4. t2执行`keyBuffer.putLong()`    ->    buffer中为 [key1, key2]
5. t1执行`keyBuffer.putInt()`        ->    buffer中为 [key1, key2, off1]
6. t2执行`keyBuffer.putInt()`        ->    buffer中为 [key1, key2, off1, off2]

此时似乎应该会产生不一致的问题。
没有任何恶意，希望能学习一下😊

**Comment by AlexZFX** [comment]
这个地方我在博客里有解释，但是还木有更新到readme里面。。
这里的keyBuffer是一个MappedByteBuffer的slice，也就是一个切片，只是共享了内存部分，但是position和limit等参数都是独立的，本来也测试过duplicate（这个是完整buffer的浅拷贝），但是性能比slice差了不止一两倍，具体的你可以查看一下ByteBuffer这一部分的源码注释。
回复晚了抱歉。😊😊
我写了一个完整的编写过程在 [这里](http://www.alexzfx.com/2018/11/20/%E7%AC%AC%E4%B8%80%E5%B1%8APOLARDB%E6%95%B0%E6%8D%AE%E5%BA%93%E6%80%A7%E8%83%BD%E5%A4%A7%E8%B5%9B%E5%88%9D%E8%B5%9B%E6%80%BB%E7%BB%93/)如果你有兴趣可以看一下。
复赛已经开始了，还木有什么好的思路，加油啊。
